### ISSUE TITLE
[Feature Request]Export SteamGuard

### ISSUE THREAD

**Issue by LittleFreak** [calendulish/steam-tools-ng#52]
**Is your feature request related to a problem? Please describe.**
I'd like to export my SteamGuard into a `STEAMGUARD.maFile`, so I can Add it to my ArchiSteamFarm.

**Describe the solution you'd like**
Adding a Button in the SteamGuard Advanced Menu to export its secrets into a file.

**Describe alternatives you've considered**

**Additional context**
It basically is a json file.
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication

**Comment by calendulish** [comment]
The steam authentication system got a rework and STNG is using that new API to login, providing an access_token and a refresh_token. The maFile format specification requires the old cookies and an oauth token that is deprecated since 2022, so it can't be implemented.

I don't know what approach archi is currently using, but if it isn't capable of automatic login using username and password, the manual method should only need your account secrets, those are already available on advanced login menu or at raw config file `steam-tools-ng-gui --config-dir`
